version: 2
jobs:
 build:
 deploy:
   steps:
     - checkout
     - run:
        name: Deploy Master to Heroku 
        command: |
          ls -l 
workflows:
 version: 2
 build_and_deploy:
    - build
    - deploy:
        requires:
          - build
