version: 2
jobs:
 build:
    docker: 
      - image: circleci/ruby:2.4.1-jessie
    steps: 
      - checkout
      - run: echo "A First Hello"
 deploy:
   docker: 
      - image: circleci/ruby:2.4.1-jessie
   steps:
     - checkout
     - run:
        name: Deploy Master to Heroku 
        command: |
          ls -l 
workflows:
 version: 2
 build-deploy:
    - build
    - deploy:
        requires:
          - build 
